name: Build and publish
on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt-get -qq -y install doxygen jekyll graphviz

    - run: jekyll --version

    - name: Add libhext documentation
      run: ./scripts/refresh-libhext-documentation.sh jekyll

    - name: Jekyll build
      shell: bash
      run: cd jekyll && jekyll build

    - name: Publish
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: jekyll/_site
